// <auto-generated>
// This file was generated by Aura Test Generator.
// </auto-generated>

using Xunit;
using NSubstitute;
using Aura.Module.Developer.Services;
using Aura.Foundation.Rag;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;

namespace Aura.Module.Developer.Services.Tests;

public class CodeGraphIndexerTests
{

    [Fact]
    public async Task IndexAsync_WhenCalled_ReturnsExpectedResult()
    {
        // Arrange
        var _roslynWorkspace = Substitute.For<IRoslynWorkspaceService>();
        var _graphService = Substitute.For<ICodeGraphService>();
        var _logger = Substitute.For<ILogger<CodeGraphIndexer>>();
        var sut = new CodeGraphIndexer(_roslynWorkspace, _graphService, _logger);

        // Act
        var result = await sut.IndexAsync("test-solutionOrProjectPath", "test-repositoryPath", CancellationToken.None);

        // Assert
        Assert.NotNull(result);
    }

    [Fact]
    public async Task ReindexAsync_WhenCalled_ReturnsExpectedResult()
    {
        // Arrange
        var _roslynWorkspace = Substitute.For<IRoslynWorkspaceService>();
        var _graphService = Substitute.For<ICodeGraphService>();
        var _logger = Substitute.For<ILogger<CodeGraphIndexer>>();
        var sut = new CodeGraphIndexer(_roslynWorkspace, _graphService, _logger);

        // Act
        var result = await sut.ReindexAsync("test-solutionOrProjectPath", "test-repositoryPath", CancellationToken.None);

        // Assert
        Assert.NotNull(result);
    }

    [Fact]
    public async Task IndexAsync_WhenAwaited_CompletesSuccessfully()
    {
        // Arrange
        var _roslynWorkspace = Substitute.For<IRoslynWorkspaceService>();
        var _graphService = Substitute.For<ICodeGraphService>();
        var _logger = Substitute.For<ILogger<CodeGraphIndexer>>();
        var sut = new CodeGraphIndexer(_roslynWorkspace, _graphService, _logger);

        // Act
        var result = await sut.IndexAsync("test-solutionOrProjectPath", "test-repositoryPath", CancellationToken.None);

        // Assert
        Assert.NotNull(result);
    }

    [Fact]
    public async Task ReindexAsync_WhenAwaited_CompletesSuccessfully()
    {
        // Arrange
        var _roslynWorkspace = Substitute.For<IRoslynWorkspaceService>();
        var _graphService = Substitute.For<ICodeGraphService>();
        var _logger = Substitute.For<ILogger<CodeGraphIndexer>>();
        var sut = new CodeGraphIndexer(_roslynWorkspace, _graphService, _logger);

        // Act
        var result = await sut.ReindexAsync("test-solutionOrProjectPath", "test-repositoryPath", CancellationToken.None);

        // Assert
        Assert.NotNull(result);
    }
}
