// <auto-generated>
// This file was generated by Aura Test Generator and enhanced manually.
// </auto-generated>

#nullable enable

using Aura.Foundation.Agents;
using Aura.Foundation.Git;
using Aura.Foundation.Llm;
using Aura.Foundation.Prompts;
using Aura.Foundation.Rag;
using Aura.Foundation.Tools;
using Aura.Module.Developer.Data;
using Aura.Module.Developer.Data.Entities;
using Aura.Module.Developer.Services;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using NSubstitute;
using Xunit;
using Aura.Module.Developer;
using Aura.Module.Developer.Services.Verification;
using Microsoft.Extensions.Logging;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Aura.Module.Developer.Tests.Services;

public class StoryServiceTests : IDisposable
{
    private readonly DeveloperDbContext _db;
    private readonly IAgentRegistry _agentRegistry;
    private readonly IPromptRegistry _promptRegistry;
    private readonly IGitWorktreeService _worktreeService;
    private readonly IGitService _gitService;
    private readonly IRagService _ragService;
    private readonly IBackgroundIndexer _backgroundIndexer;
    private readonly ICodebaseContextService _codebaseContextService;
    private readonly IToolRegistry _toolRegistry;
    private readonly IReActExecutor _reactExecutor;
    private readonly ILlmProviderRegistry _llmProviderRegistry;
    private readonly IStoryVerificationService _verificationService;
    private readonly IStepExecutorRegistry _stepExecutorRegistry;
    private readonly IQualityGateService _qualityGateService;
    private readonly IOptions<DeveloperModuleOptions> _options;
    private readonly StoryService _sut;

    public StoryServiceTests()
    {
        // Use EF Core InMemory database for testing
        var dbOptions = new DbContextOptionsBuilder<DeveloperDbContext>()
            .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
            .Options;
        _db = new DeveloperDbContext(dbOptions);

        // Create mocks for all dependencies
        _agentRegistry = Substitute.For<IAgentRegistry>();
        _promptRegistry = Substitute.For<IPromptRegistry>();
        _worktreeService = Substitute.For<IGitWorktreeService>();
        // Set up worktree service to return failure (simulates non-git repo or disabled)
        _worktreeService.CreateAsync(Arg.Any<string>(), Arg.Any<string>(), Arg.Any<string?>(), Arg.Any<string?>(), Arg.Any<CancellationToken>())
            .Returns(Task.FromResult(GitResult<WorktreeInfo>.Fail("Test mode - no worktree creation")));
        _gitService = Substitute.For<IGitService>();
        _ragService = Substitute.For<IRagService>();
        _backgroundIndexer = Substitute.For<IBackgroundIndexer>();
        _codebaseContextService = Substitute.For<ICodebaseContextService>();
        _toolRegistry = Substitute.For<IToolRegistry>();
        _reactExecutor = Substitute.For<IReActExecutor>();
        _llmProviderRegistry = Substitute.For<ILlmProviderRegistry>();
        _verificationService = Substitute.For<IStoryVerificationService>();
        _stepExecutorRegistry = Substitute.For<IStepExecutorRegistry>();
        _qualityGateService = Substitute.For<IQualityGateService>();
        _options = Options.Create(new DeveloperModuleOptions { BranchPrefix = "workflow/" });

        _sut = new StoryService(
            _db,
            _agentRegistry,
            _promptRegistry,
            _worktreeService,
            _gitService,
            _ragService,
            _backgroundIndexer,
            _codebaseContextService,
            _toolRegistry,
            _reactExecutor,
            _llmProviderRegistry,
            _verificationService,
            _stepExecutorRegistry,
            _qualityGateService,
            _options,
            NullLogger<StoryService>.Instance);
    }

    public void Dispose()
    {
        _db.Dispose();
    }

    #region CreateAsync Tests

    [Fact]
    public async Task CreateAsync_WithValidTitle_CreatesWorkflow()
    {
        // Act
        var result = await _sut.CreateAsync("Test Workflow");

        // Assert
        result.Should().NotBeNull();
        result.Title.Should().Be("Test Workflow");
        result.Status.Should().Be(StoryStatus.Created);
        result.Id.Should().NotBeEmpty();
    }

    [Fact]
    public async Task CreateAsync_WithDescription_SetsDescription()
    {
        // Act
        var result = await _sut.CreateAsync("Test", description: "My description");

        // Assert
        result.Description.Should().Be("My description");
    }

    [Fact]
    public async Task CreateAsync_WithRepositoryPath_SetsRepositoryPath()
    {
        // Act
        var result = await _sut.CreateAsync("Test", repositoryPath: "/path/to/repo");

        // Assert
        result.RepositoryPath.Should().Be("/path/to/repo");
    }

    [Fact]
    public async Task CreateAsync_WithAutomationMode_SetsAutomationMode()
    {
        // Act
        var result = await _sut.CreateAsync("Test", automationMode: AutomationMode.Autonomous);

        // Assert
        result.AutomationMode.Should().Be(AutomationMode.Autonomous);
    }

    [Fact]
    public async Task CreateAsync_GeneratesBranchName()
    {
        // Act
        var result = await _sut.CreateAsync("My Feature");

        // Assert
        result.GitBranch.Should().StartWith("workflow/my-feature-");
    }

    [Fact]
    public async Task CreateAsync_PersistsToDatabase()
    {
        // Act
        var result = await _sut.CreateAsync("Persisted Workflow");

        // Assert
        var fromDb = await _db.Workflows.FindAsync(result.Id);
        fromDb.Should().NotBeNull();
        fromDb!.Title.Should().Be("Persisted Workflow");
    }

    #endregion

    #region GetByIdAsync Tests

    [Fact]
    public async Task GetByIdAsync_WithExistingId_ReturnsWorkflow()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("Existing");

        // Act
        var result = await _sut.GetByIdAsync(workflow.Id);

        // Assert
        result.Should().NotBeNull();
        result!.Id.Should().Be(workflow.Id);
    }

    [Fact]
    public async Task GetByIdAsync_WithNonExistingId_ReturnsNull()
    {
        // Act
        var result = await _sut.GetByIdAsync(Guid.NewGuid());

        // Assert
        result.Should().BeNull();
    }

    #endregion

    #region ListAsync Tests

    [Fact]
    public async Task ListAsync_ReturnsAllWorkflows()
    {
        // Arrange
        await _sut.CreateAsync("Workflow 1");
        await _sut.CreateAsync("Workflow 2");
        await _sut.CreateAsync("Workflow 3");

        // Act
        var result = await _sut.ListAsync();

        // Assert
        result.Should().HaveCount(3);
    }

    [Fact]
    public async Task ListAsync_WithStatusFilter_ReturnsFilteredWorkflows()
    {
        // Arrange
        var w1 = await _sut.CreateAsync("Created Workflow");
        var w2 = await _sut.CreateAsync("Completed Workflow");
        w2.Status = StoryStatus.Completed;
        await _sut.UpdateAsync(w2);

        // Act
        var result = await _sut.ListAsync(status: StoryStatus.Created);

        // Assert
        result.Should().HaveCount(1);
        result[0].Title.Should().Be("Created Workflow");
    }

    // Note: ListAsync with repositoryPath filter uses PostgreSQL ILike which doesn't work in InMemory
    // This is covered by integration tests instead

    #endregion

    #region DeleteAsync Tests

    [Fact]
    public async Task DeleteAsync_RemovesWorkflowFromDatabase()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("To Delete");
        var id = workflow.Id;

        // Act
        await _sut.DeleteAsync(id);

        // Assert
        var fromDb = await _db.Workflows.FindAsync(id);
        fromDb.Should().BeNull();
    }

    #endregion

    #region UpdateAsync Tests

    [Fact]
    public async Task UpdateAsync_ModifiesWorkflow()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("Original Title");
        workflow.Title = "Updated Title";

        // Act
        await _sut.UpdateAsync(workflow);

        // Assert
        var fromDb = await _db.Workflows.FindAsync(workflow.Id);
        fromDb!.Title.Should().Be("Updated Title");
    }

    [Fact]
    public async Task UpdateAsync_UpdatesTimestamp()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("Test");
        var originalUpdatedAt = workflow.UpdatedAt;
        await Task.Delay(50); // Ensure time passes
        workflow.Title = "Updated";

        // Act
        await _sut.UpdateAsync(workflow);

        // Assert
        var fromDb = await _db.Workflows.FindAsync(workflow.Id);
        fromDb!.UpdatedAt.Should().BeOnOrAfter(originalUpdatedAt);
    }

    #endregion

    #region CompleteAsync Tests

    [Fact]
    public async Task CompleteAsync_SetsStatusToCompleted()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("To Complete");

        // Act
        var result = await _sut.CompleteAsync(workflow.Id);

        // Assert
        result.Status.Should().Be(StoryStatus.Completed);
    }

    #endregion

    #region CancelAsync Tests

    [Fact]
    public async Task CancelAsync_SetsStatusToCancelled()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("To Cancel");

        // Act
        var result = await _sut.CancelAsync(workflow.Id);

        // Assert
        result.Status.Should().Be(StoryStatus.Cancelled);
    }

    #endregion

    #region AddStepAsync Tests

    [Fact]
    public async Task AddStepAsync_AddsStepToWorkflow()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("With Steps");

        // Act
        var step = await _sut.AddStepAsync(
            workflow.Id,
            "Step 1",
            "code-review",
            description: "Review the code");

        // Assert
        step.Should().NotBeNull();
        step.Name.Should().Be("Step 1");
        step.Capability.Should().Be("code-review");
        step.Description.Should().Be("Review the code");
    }

    [Fact]
    public async Task AddStepAsync_AssignsIncrementingOrder()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("With Steps");

        // Act
        var step1 = await _sut.AddStepAsync(workflow.Id, "Step 1", "capability1");
        var step2 = await _sut.AddStepAsync(workflow.Id, "Step 2", "capability2");

        // Assert - steps are ordered sequentially, second is after first
        step2.Order.Should().BeGreaterThan(step1.Order);
    }

    #endregion

    #region RemoveStepAsync Tests

    [Fact]
    public async Task RemoveStepAsync_RemovesStepFromWorkflow()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("With Steps");
        var step = await _sut.AddStepAsync(workflow.Id, "To Remove", "capability");

        // Act
        await _sut.RemoveStepAsync(workflow.Id, step.Id);

        // Assert
        var fromDb = await _db.WorkflowSteps.FindAsync(step.Id);
        fromDb.Should().BeNull();
    }

    #endregion

    #region GetByIdWithStepsAsync Tests

    [Fact]
    public async Task GetByIdWithStepsAsync_ReturnsWorkflowWithSteps()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("With Steps");
        await _sut.AddStepAsync(workflow.Id, "Step 1", "cap1");
        await _sut.AddStepAsync(workflow.Id, "Step 2", "cap2");

        // Act
        var result = await _sut.GetByIdWithStepsAsync(workflow.Id);

        // Assert
        result.Should().NotBeNull();
        result!.Steps.Should().HaveCount(2);
    }

    #endregion

    #region ApproveStepAsync Tests

    [Fact]
    public async Task ApproveStepAsync_WithCompletedStep_SetsApprovalToApproved()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("Test");
        var step = await _sut.AddStepAsync(workflow.Id, "Step", "cap");

        // Mark step as completed first (required for approval)
        step.Status = StepStatus.Completed;
        await _sut.UpdateStepAsync(step);

        // Act
        var result = await _sut.ApproveStepAsync(workflow.Id, step.Id);

        // Assert
        result.Approval.Should().Be(StepApproval.Approved);
    }

    [Fact]
    public async Task ApproveStepAsync_WithPendingStep_ThrowsException()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("Test");
        var step = await _sut.AddStepAsync(workflow.Id, "Step", "cap");

        // Act
        var act = () => _sut.ApproveStepAsync(workflow.Id, step.Id);

        // Assert
        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("*Cannot approve step*");
    }

    #endregion

    #region SkipStepAsync Tests

    [Fact]
    public async Task SkipStepAsync_SetsStepStatusToSkipped()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("Test");
        var step = await _sut.AddStepAsync(workflow.Id, "Step", "cap");

        // Act
        var result = await _sut.SkipStepAsync(workflow.Id, step.Id, reason: "Not needed");

        // Assert
        result.Status.Should().Be(StepStatus.Skipped);
    }

    #endregion

    #region ResetStepAsync Tests

    [Fact]
    public async Task ResetStepAsync_SetsStepStatusToPending()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("Test");
        var step = await _sut.AddStepAsync(workflow.Id, "Step", "cap");

        // Mark step as skipped (a non-pending status)
        await _sut.SkipStepAsync(workflow.Id, step.Id, "Test skip");

        // Act
        var result = await _sut.ResetStepAsync(workflow.Id, step.Id);

        // Assert
        result.Status.Should().Be(StepStatus.Pending);
    }

    #endregion

    #region RejectStepAsync Tests

    [Fact]
    public async Task RejectStepAsync_SetsApprovalToRejectedAndResetsStatus()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("Test");
        var step = await _sut.AddStepAsync(workflow.Id, "Step", "cap");

        // First complete the step (RejectStepAsync requires Completed status)
        step.Status = StepStatus.Completed;
        step.Output = "Some output";
        await _sut.UpdateStepAsync(step);

        // Act
        var result = await _sut.RejectStepAsync(workflow.Id, step.Id, "Needs changes");

        // Assert
        result.Approval.Should().Be(StepApproval.Rejected);
        result.ApprovalFeedback.Should().Be("Needs changes");
        result.Status.Should().Be(StepStatus.Pending); // Reset to pending for re-execution
    }

    #endregion

    #region ReassignStepAsync Tests

    [Fact]
    public async Task ReassignStepAsync_UpdatesAgentId()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("Test");
        var step = await _sut.AddStepAsync(workflow.Id, "Step", "cap");

        // Act
        var result = await _sut.ReassignStepAsync(workflow.Id, step.Id, "new-agent-id");

        // Assert
        result.AssignedAgentId.Should().Be("new-agent-id");
    }

    #endregion

    #region GetByWorktreePathAsync Tests

    // Note: GetByWorktreePathAsync uses PostgreSQL's ILike function which isn't supported
    // by InMemory database. These tests require integration tests with a real PostgreSQL database.

    #endregion

    #region UpdateStepDescriptionAsync Tests

    [Fact]
    public async Task UpdateStepDescriptionAsync_UpdatesDescription()
    {
        // Arrange
        var workflow = await _sut.CreateAsync("Test");
        var step = await _sut.AddStepAsync(workflow.Id, "Step", "cap", description: "Old description");

        // Act
        var result = await _sut.UpdateStepDescriptionAsync(workflow.Id, step.Id, "New description");

        // Assert
        result.Description.Should().Be("New description");
    }

    #endregion
}
