// <auto-generated>
// This file was generated by Aura Test Generator and enhanced manually.
// </auto-generated>

#nullable enable

using Xunit;
using NSubstitute;
using FluentAssertions;
using Aura.Module.Developer.Agents;
using Aura.Foundation.Agents;
using Microsoft.Extensions.Logging;
using System.Linq;

namespace Aura.Module.Developer.Agents.Tests;

public class DeveloperAgentProviderTests
{
    private readonly ILoggerFactory _loggerFactory;
    private readonly DeveloperAgentProvider _sut;

    public DeveloperAgentProviderTests()
    {
        _loggerFactory = Substitute.For<ILoggerFactory>();
        _loggerFactory.CreateLogger(Arg.Any<string>()).Returns(Substitute.For<ILogger>());
        _sut = new DeveloperAgentProvider(_loggerFactory);
    }

    [Fact]
    public void GetAgents_WhenCalled_ReturnsExpectedResult()
    {
        // Act
        var result = _sut.GetAgents();

        // Assert
        result.Should().NotBeNull();
        result.Should().NotBeEmpty();
    }

    [Fact]
    public void GetAgents_ReturnsCSharpIngesterAgent()
    {
        // Act
        var agents = _sut.GetAgents().ToList();

        // Assert
        agents.Should().Contain(a => a.GetType() == typeof(CSharpIngesterAgent));
    }

    [Fact]
    public void GetAgents_ReturnsTreeSitterIngesterAgent()
    {
        // Act
        var agents = _sut.GetAgents().ToList();

        // Assert
        agents.Should().Contain(a => a.GetType() == typeof(TreeSitterIngesterAgent));
    }

    [Fact]
    public void GetAgents_ReturnsExactlyTwoAgents()
    {
        // Act
        var agents = _sut.GetAgents().ToList();

        // Assert
        agents.Should().HaveCount(2);
    }

    [Fact]
    public void GetAgents_CSharpIngesterHasHigherPriorityThanTreeSitter()
    {
        // Act
        var agents = _sut.GetAgents().ToList();
        var csharpIngester = agents.OfType<CSharpIngesterAgent>().First();
        var treeSitterIngester = agents.OfType<TreeSitterIngesterAgent>().First();

        // Assert - Lower priority number = higher priority = more specialized
        csharpIngester.Metadata.Priority.Should().BeLessThan(treeSitterIngester.Metadata.Priority);
    }

    [Fact]
    public void GetAgents_AllAgentsHaveValidMetadata()
    {
        // Act
        var agents = _sut.GetAgents().ToList();

        // Assert
        foreach (var agent in agents)
        {
            agent.Metadata.Should().NotBeNull();
            agent.Metadata.Name.Should().NotBeNullOrEmpty();
            agent.Metadata.Description.Should().NotBeNullOrEmpty();
        }
    }

    [Fact]
    public void GetAgents_IngestersHaveIngestCapabilities()
    {
        // Act
        var agents = _sut.GetAgents().ToList();
        var ingesters = agents.Where(a =>
            a.GetType() == typeof(CSharpIngesterAgent) ||
            a.GetType() == typeof(TreeSitterIngesterAgent)).ToList();

        // Assert
        foreach (var ingester in ingesters)
        {
            // Ingest capabilities follow pattern "ingest" or "ingest:*"
            ingester.Metadata.Capabilities.Should().Contain(c =>
                c == "ingest" || c.StartsWith("ingest:"));
        }
    }
}
