// <auto-generated>
// This file was generated by Aura Test Generator.
// </auto-generated>

using Xunit;
using NSubstitute;
using Aura.Module.Developer.Agents;
using Aura.Foundation.Agents;
using Aura.Foundation.Llm;
using Aura.Foundation.Tools;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;

namespace Aura.Module.Developer.Agents.Tests;

public class DeveloperAgentProviderTests
{

    [Fact]
    public void GetAgents_WhenCalled_ReturnsExpectedResult()
    {
        // Arrange
        var _loggerFactory = Substitute.For<ILoggerFactory>();
        var _llmRegistry = Substitute.For<ILlmProviderRegistry>();
        var _reactExecutor = Substitute.For<IReActExecutor>();
        var _toolRegistry = Substitute.For<IToolRegistry>();
        var sut = new DeveloperAgentProvider(_loggerFactory, _llmRegistry, _reactExecutor, _toolRegistry);

        // Act
        var result = sut.GetAgents();

        // Assert
        Assert.NotNull(result);
        Assert.NotEmpty(result);
    }
}
