// <auto-generated>
// This file was generated by Aura Test Generator.
// </auto-generated>

using Xunit;
using NSubstitute;
using FluentAssertions;
using Aura.Module.Developer.Agents;
using Aura.Foundation.Shell;
using Aura.Foundation.Tools;
using Microsoft.Extensions.Logging.Abstractions;

namespace Aura.Module.Developer.Agents.Tests;

public class LanguageToolFactoryTests
{
    [Fact]
    public void RegisterToolsFromConfig_WithEmptyConfig_ReturnsEmptyList()
    {
        // Arrange
        var registry = Substitute.For<IToolRegistry>();
        var processRunner = Substitute.For<IProcessRunner>();
        var config = new LanguageConfig
        {
            Language = new LanguageMetadata { Id = "test", Name = "Test" }
        };
        var logger = NullLogger.Instance;

        // Act
        var result = LanguageToolFactory.RegisterToolsFromConfig(registry, processRunner, config, logger);

        // Assert
        result.Should().NotBeNull();
        result.Should().BeEmpty(); // No tools defined in config
    }

    [Fact]
    public void RegisterToolsFromConfig_WithToolDefinition_RegistersTool()
    {
        // Arrange
        var registry = Substitute.For<IToolRegistry>();
        var processRunner = Substitute.For<IProcessRunner>();
        var config = new LanguageConfig
        {
            Language = new LanguageMetadata { Id = "python", Name = "Python" },
            Tools = new Dictionary<string, ToolConfig>
            {
                ["format"] = new ToolConfig
                {
                    Id = "python_format",
                    Description = "Format Python code",
                    Command = "black",
                    Args = ["{file}"]
                }
            }
        };
        var logger = NullLogger.Instance;

        // Act
        var result = LanguageToolFactory.RegisterToolsFromConfig(registry, processRunner, config, logger);

        // Assert
        result.Should().NotBeNull();
        result.Should().ContainSingle();
        result[0].Should().Be("python_format");
    }
}
