// <auto-generated>
// This file was generated by Aura Test Generator.
// </auto-generated>

namespace Aura.Module.Developer.Agents.Tests;

using System.IO.Abstractions.TestingHelpers;
using Aura.Module.Developer.Agents;
using FluentAssertions;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;

public class LanguageConfigLoaderTests
{
    private readonly MockFileSystem _fileSystem = new();

    private LanguageConfigLoader CreateSut() => new(_fileSystem, NullLogger<LanguageConfigLoader>.Instance);

    private const string ValidYaml = """
        language:
          id: python
          name: Python
          extensions:
            - .py
        capabilities:
          - coding
        tools:
          lint:
            id: python.lint
            command: ruff
        """;

    [Fact]
    public async Task LoadAllAsync_WithValidDirectory_ReturnsConfigs()
    {
        // Arrange
        _fileSystem.AddFile("/languages/python.yaml", new MockFileData(ValidYaml));
        var sut = CreateSut();

        // Act
        var result = await sut.LoadAllAsync("/languages");

        // Assert
        result.Should().HaveCount(1);
        result[0].Language.Id.Should().Be("python");
    }

    [Fact]
    public void Validate_WithValidConfig_ReturnsValid()
    {
        // Arrange
        var config = new LanguageConfig
        {
            Language = new LanguageMetadata { Id = "python", Name = "Python" },
            Capabilities = ["coding"],
            Tools = new Dictionary<string, ToolConfig>
            {
                ["lint"] = new() { Id = "python.lint", Command = "ruff" }
            }
        };
        var sut = CreateSut();

        // Act
        var result = sut.Validate(config);

        // Assert
        result.IsValid.Should().BeTrue();
        result.Errors.Should().BeEmpty();
    }

    [Fact]
    public async Task LoadAsync_WithValidFile_ReturnsConfig()
    {
        // Arrange
        _fileSystem.AddFile("/languages/python.yaml", new MockFileData(ValidYaml));
        var sut = CreateSut();

        // Act
        var result = await sut.LoadAsync("/languages/python.yaml");

        // Assert
        result.Should().NotBeNull();
        result!.Language.Id.Should().Be("python");
        result.Language.Name.Should().Be("Python");
    }

    [Fact]
    public async Task LoadAllAsync_WithNonExistentDirectory_ReturnsEmpty()
    {
        // Arrange
        var sut = CreateSut();

        // Act
        var result = await sut.LoadAllAsync("/nonexistent");

        // Assert
        result.Should().BeEmpty();
    }

    [Fact]
    public async Task LoadAsync_WithInvalidYaml_ReturnsNull()
    {
        _fileSystem.AddFile("/invalid.yaml", new MockFileData("not: valid: yaml: ::"));
        var sut = CreateSut();

        // Act
        var result = await sut.LoadAsync("/invalid.yaml");

        // Assert
        result.Should().BeNull();
    }

    [Fact]
    public async Task LoadAsync_WithNonExistentFile_ReturnsNull()
    {
        var sut = CreateSut();

        // Act
        var result = await sut.LoadAsync("/does/not/exist.yaml");

        // Assert
        result.Should().BeNull();
    }

    [Fact]
    public void Validate_WithMissingLanguageId_ReturnsErrors()
    {
        var config = new LanguageConfig
        {
            Language = new LanguageMetadata { Id = string.Empty, Name = "Python" },
            Capabilities = ["coding"],
            Tools = new Dictionary<string, ToolConfig>
            {
                ["lint"] = new() { Id = "python.lint", Command = "ruff" }
            }
        };
        var sut = CreateSut();

        // Act
        var result = sut.Validate(config);

        // Assert
        result.IsValid.Should().BeFalse();
        result.Errors.Should().Contain(e => e.Contains("language.id"));
    }

    [Fact]
    public void Validate_WithNoCapabilities_ReturnsErrors()
    {
        var config = new LanguageConfig
        {
            Language = new LanguageMetadata { Id = "python", Name = "Python" },
            Capabilities = [],
            Tools = new Dictionary<string, ToolConfig>
            {
                ["lint"] = new() { Id = "python.lint", Command = "ruff" }
            }
        };
        var sut = CreateSut();

        // Act
        var result = sut.Validate(config);

        // Assert
        result.IsValid.Should().BeFalse();
        result.Errors.Should().Contain(e => e.Contains("capability"));
    }

    [Fact]
    public void Validate_WithToolMissingCommand_ReturnsErrors()
    {
        var config = new LanguageConfig
        {
            Language = new LanguageMetadata { Id = "python", Name = "Python" },
            Capabilities = ["coding"],
            Tools = new Dictionary<string, ToolConfig>
            {
                ["lint"] = new() { Id = "python.lint", Command = string.Empty }
            }
        };
        var sut = CreateSut();

        // Act
        var result = sut.Validate(config);

        // Assert
        result.IsValid.Should().BeFalse();
        result.Errors.Should().Contain(e => e.Contains("'lint'") && e.Contains("command"));
    }

    [Fact]
    public async Task LoadAllAsync_SkipsInvalidFiles()
    {
        var validYaml = """
    language:
      id: python
      name: Python
    capabilities:
      - coding
    tools:
      lint:
        id: python.lint
        command: ruff
    """;
        var invalidYaml = """
    language:
      name: NoId
    capabilities: []
    """;

        _fileSystem.AddFile("/languages/valid.yaml", new MockFileData(validYaml));
        _fileSystem.AddFile("/languages/invalid.yaml", new MockFileData(invalidYaml));
        var sut = CreateSut();

        // Act
        var result = await sut.LoadAllAsync("/languages");

        // Assert
        result.Should().HaveCount(1);
        result[0].Language.Id.Should().Be("python");
    }
}
