// <auto-generated />
using System;
using Aura.Module.Researcher.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Aura.Module.Researcher.Migrations
{
    [DbContext(typeof(ResearcherDbContext))]
    [Migration("20260202124310_InitialResearcher")]
    partial class InitialResearcher
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aura.Module.Researcher.Data.Entities.Concept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("Aura.Module.Researcher.Data.Entities.ConceptLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromConceptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToConceptId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromConceptId");

                    b.HasIndex("SourceId");

                    b.HasIndex("ToConceptId");

                    b.ToTable("ConceptLinks");
                });

            modelBuilder.Entity("Aura.Module.Researcher.Data.Entities.Excerpt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Annotation")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Excerpts");
                });

            modelBuilder.Entity("Aura.Module.Researcher.Data.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abstract")
                        .HasColumnType("text");

                    b.Property<string>("ArxivId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Authors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("CitationCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Doi")
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)");

                    b.Property<string>("MarkdownPath")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReadingStatus")
                        .HasColumnType("integer");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArxivId");

                    b.HasIndex("Doi");

                    b.HasIndex("ReadingStatus");

                    b.HasIndex("SourceType");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Aura.Module.Researcher.Data.Entities.SourceConcept", b =>
                {
                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimaryTopic")
                        .HasColumnType("boolean");

                    b.Property<int>("MentionCount")
                        .HasColumnType("integer");

                    b.HasKey("SourceId", "ConceptId");

                    b.HasIndex("ConceptId");

                    b.ToTable("SourceConcepts");
                });

            modelBuilder.Entity("Aura.Module.Researcher.Data.Entities.Synthesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Focus")
                        .HasColumnType("text");

                    b.PrimitiveCollection<Guid[]>("SourceIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("Style")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Syntheses");
                });

            modelBuilder.Entity("Aura.Module.Researcher.Data.Entities.ConceptLink", b =>
                {
                    b.HasOne("Aura.Module.Researcher.Data.Entities.Concept", "FromConcept")
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("FromConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aura.Module.Researcher.Data.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aura.Module.Researcher.Data.Entities.Concept", "ToConcept")
                        .WithMany("IncomingLinks")
                        .HasForeignKey("ToConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromConcept");

                    b.Navigation("Source");

                    b.Navigation("ToConcept");
                });

            modelBuilder.Entity("Aura.Module.Researcher.Data.Entities.Excerpt", b =>
                {
                    b.HasOne("Aura.Module.Researcher.Data.Entities.Source", "Source")
                        .WithMany("Excerpts")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Aura.Module.Researcher.Data.Entities.SourceConcept", b =>
                {
                    b.HasOne("Aura.Module.Researcher.Data.Entities.Concept", "Concept")
                        .WithMany("SourceConcepts")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aura.Module.Researcher.Data.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Aura.Module.Researcher.Data.Entities.Concept", b =>
                {
                    b.Navigation("IncomingLinks");

                    b.Navigation("OutgoingLinks");

                    b.Navigation("SourceConcepts");
                });

            modelBuilder.Entity("Aura.Module.Researcher.Data.Entities.Source", b =>
                {
                    b.Navigation("Excerpts");
                });
#pragma warning restore 612, 618
        }
    }
}
