// <auto-generated>
// This file was generated by Aura Test Generator.
// </auto-generated>

using Xunit;
using NSubstitute;
using FluentAssertions;
using Aura.Module.Developer.Tools;
using Aura.Foundation.Agents;
using Aura.Foundation.Shell;
using Aura.Foundation.Tools;
using Microsoft.Extensions.Logging.Abstractions;

namespace Aura.Module.Developer.Tools.Tests;

public class BuildFixLoopToolsTests
{
    [Fact]
    public void RegisterBuildFixLoopTools_WhenCalled_RegistersToolsInRegistry()
    {
        // Arrange
        var registry = Substitute.For<IToolRegistry>();
        var processRunner = Substitute.For<IProcessRunner>();
        var agentRegistry = Substitute.For<IAgentRegistry>();
        var logger = NullLogger.Instance;

        // Act
        BuildFixLoopTools.RegisterBuildFixLoopTools(registry, processRunner, agentRegistry, logger);

        // Assert - should register at least one tool
        registry.Received().RegisterTool(Arg.Any<ToolDefinition>());
    }

    [Fact]
    public void RegisterBuildFixLoopTools_RegistersDotnetBuildUntilSuccessTool()
    {
        // Arrange
        var registry = Substitute.For<IToolRegistry>();
        var processRunner = Substitute.For<IProcessRunner>();
        var agentRegistry = Substitute.For<IAgentRegistry>();
        var logger = NullLogger.Instance;

        // Act
        BuildFixLoopTools.RegisterBuildFixLoopTools(registry, processRunner, agentRegistry, logger);

        // Assert - should register the dotnet.build_until_success tool
        registry.Received().RegisterTool(Arg.Is<ToolDefinition>(t => t.ToolId == "dotnet.build_until_success"));
    }
}
