// <auto-generated>
// This file was generated by Aura Test Generator.
// </auto-generated>

#nullable enable

using Xunit;
using NSubstitute;
using FluentAssertions;
using Aura.Module.Developer.Tools;
using Aura.Foundation.Rag;
using Aura.Foundation.Tools;
using Microsoft.Extensions.Logging.Abstractions;

namespace Aura.Module.Developer.Tools.Tests;

public class VisualizationToolsTests
{
    [Fact]
    public void RegisterVisualizationTools_WhenCalled_RegistersToolsInRegistry()
    {
        // Arrange
        var registry = Substitute.For<IToolRegistry>();
        var codeGraphService = Substitute.For<ICodeGraphService>();
        var logger = NullLogger.Instance;

        // Act
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, logger);

        // Assert - should register at least one tool
        registry.Received().RegisterTool(Arg.Any<ToolDefinition>());
    }

    [Fact]
    public void RegisterVisualizationTools_Registers3Tools()
    {
        // Arrange
        var registry = Substitute.For<IToolRegistry>();
        var codeGraphService = Substitute.For<ICodeGraphService>();
        var logger = NullLogger.Instance;

        // Act
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, logger);

        // Assert - registers exactly 3 tools (dependencies, class hierarchy, call graph)
        registry.Received(3).RegisterTool(Arg.Any<ToolDefinition>());
    }

    [Fact]
    public void RegisterVisualizationTools_RegistersDependenciesTool()
    {
        // Arrange
        var registry = Substitute.For<IToolRegistry>();
        var codeGraphService = Substitute.For<ICodeGraphService>();
        var logger = NullLogger.Instance;

        // Act
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, logger);

        // Assert
        registry.Received().RegisterTool(Arg.Is<ToolDefinition>(t => t.ToolId == "graph.visualize_dependencies"));
    }

    [Fact]
    public void RegisterVisualizationTools_RegistersClassHierarchyTool()
    {
        // Arrange
        var registry = Substitute.For<IToolRegistry>();
        var codeGraphService = Substitute.For<ICodeGraphService>();
        var logger = NullLogger.Instance;

        // Act
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, logger);

        // Assert
        registry.Received().RegisterTool(Arg.Is<ToolDefinition>(t => t.ToolId == "graph.visualize_class_hierarchy"));
    }

    [Fact]
    public void RegisterVisualizationTools_RegistersCallGraphTool()
    {
        // Arrange
        var registry = Substitute.For<IToolRegistry>();
        var codeGraphService = Substitute.For<ICodeGraphService>();
        var logger = NullLogger.Instance;

        // Act
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, logger);

        // Assert
        registry.Received().RegisterTool(Arg.Is<ToolDefinition>(t => t.ToolId == "graph.visualize_call_graph"));
    }

    [Fact]
    public void RegisterVisualizationTools_AllToolsHaveDescriptions()
    {
        // Arrange
        var capturedTools = new List<ToolDefinition>();
        var registry = Substitute.For<IToolRegistry>();
        registry.When(r => r.RegisterTool(Arg.Any<ToolDefinition>()))
            .Do(ci => capturedTools.Add(ci.Arg<ToolDefinition>()));

        var codeGraphService = Substitute.For<ICodeGraphService>();
        var logger = NullLogger.Instance;

        // Act
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, logger);

        // Assert
        capturedTools.Should().HaveCount(3);
        capturedTools.Should().AllSatisfy(t =>
        {
            t.Description.Should().NotBeNullOrEmpty();
            t.Name.Should().NotBeNullOrEmpty();
        });
    }

    [Fact]
    public void RegisterVisualizationTools_AllToolsHaveHandlers()
    {
        // Arrange
        var capturedTools = new List<ToolDefinition>();
        var registry = Substitute.For<IToolRegistry>();
        registry.When(r => r.RegisterTool(Arg.Any<ToolDefinition>()))
            .Do(ci => capturedTools.Add(ci.Arg<ToolDefinition>()));

        var codeGraphService = Substitute.For<ICodeGraphService>();
        var logger = NullLogger.Instance;

        // Act
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, logger);

        // Assert
        capturedTools.Should().HaveCount(3);
        capturedTools.Should().AllSatisfy(t => t.Handler.Should().NotBeNull());
    }

    [Fact]
    public void RegisterVisualizationTools_AllToolsHaveInputSchemas()
    {
        // Arrange
        var capturedTools = new List<ToolDefinition>();
        var registry = Substitute.For<IToolRegistry>();
        registry.When(r => r.RegisterTool(Arg.Any<ToolDefinition>()))
            .Do(ci => capturedTools.Add(ci.Arg<ToolDefinition>()));

        var codeGraphService = Substitute.For<ICodeGraphService>();
        var logger = NullLogger.Instance;

        // Act
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, logger);

        // Assert
        capturedTools.Should().HaveCount(3);
        capturedTools.Should().AllSatisfy(t =>
        {
            t.InputSchema.Should().NotBeNullOrEmpty();
            t.InputSchema.Should().Contain("properties"); // Valid JSON schema
        });
    }

    [Fact]
    public void RegisterVisualizationTools_DependenciesTool_HasProjectNameInSchema()
    {
        // Arrange
        var capturedTools = new List<ToolDefinition>();
        var registry = Substitute.For<IToolRegistry>();
        registry.When(r => r.RegisterTool(Arg.Any<ToolDefinition>()))
            .Do(ci => capturedTools.Add(ci.Arg<ToolDefinition>()));

        var codeGraphService = Substitute.For<ICodeGraphService>();
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, NullLogger.Instance);

        // Assert
        var tool = capturedTools.First(t => t.ToolId == "graph.visualize_dependencies");
        tool.InputSchema.Should().Contain("projectName");
        tool.InputSchema.Should().Contain("workspacePath");
    }

    [Fact]
    public void RegisterVisualizationTools_ClassHierarchyTool_HasTypeNameInSchema()
    {
        // Arrange
        var capturedTools = new List<ToolDefinition>();
        var registry = Substitute.For<IToolRegistry>();
        registry.When(r => r.RegisterTool(Arg.Any<ToolDefinition>()))
            .Do(ci => capturedTools.Add(ci.Arg<ToolDefinition>()));

        var codeGraphService = Substitute.For<ICodeGraphService>();
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, NullLogger.Instance);

        // Assert
        var tool = capturedTools.First(t => t.ToolId == "graph.visualize_class_hierarchy");
        tool.InputSchema.Should().Contain("typeName");
    }

    [Fact]
    public void RegisterVisualizationTools_CallGraphTool_HasMethodNameInSchema()
    {
        // Arrange
        var capturedTools = new List<ToolDefinition>();
        var registry = Substitute.For<IToolRegistry>();
        registry.When(r => r.RegisterTool(Arg.Any<ToolDefinition>()))
            .Do(ci => capturedTools.Add(ci.Arg<ToolDefinition>()));

        var codeGraphService = Substitute.For<ICodeGraphService>();
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, NullLogger.Instance);

        // Assert
        var tool = capturedTools.First(t => t.ToolId == "graph.visualize_call_graph");
        tool.InputSchema.Should().Contain("methodName");
    }

    // ========================================================================
    // SanitizeForMermaid Tests (internal method)
    // ========================================================================

    [Fact]
    public void SanitizeForMermaid_WithSimpleName_ReturnsUnchanged()
    {
        // Act
        var result = VisualizationTools.SanitizeForMermaid("MyClass");

        // Assert
        result.Should().Be("MyClass");
    }

    [Fact]
    public void SanitizeForMermaid_WithGenericType_RemovesAngleBrackets()
    {
        // Act
        var result = VisualizationTools.SanitizeForMermaid("List<string>");

        // Assert
        result.Should().Be("Liststring");
    }

    [Fact]
    public void SanitizeForMermaid_WithNamespace_RemovesDots()
    {
        // Act
        var result = VisualizationTools.SanitizeForMermaid("System.Collections.Generic");

        // Assert
        result.Should().Be("SystemCollectionsGeneric");
    }

    [Fact]
    public void SanitizeForMermaid_WithSpecialCharacters_RemovesThem()
    {
        // Act
        var result = VisualizationTools.SanitizeForMermaid("Method(int, string)");

        // Assert - parentheses, comma, and space are removed
        result.Should().Be("Methodintstring");
    }

    [Fact]
    public void SanitizeForMermaid_WithUnderscores_PreservesThem()
    {
        // Act
        var result = VisualizationTools.SanitizeForMermaid("my_method_name");

        // Assert
        result.Should().Be("my_method_name");
    }

    [Fact]
    public void SanitizeForMermaid_WithNumbers_PreservesThem()
    {
        // Act
        var result = VisualizationTools.SanitizeForMermaid("Method123");

        // Assert
        result.Should().Be("Method123");
    }

    [Fact]
    public void SanitizeForMermaid_WithEmptyString_ReturnsEmpty()
    {
        // Act
        var result = VisualizationTools.SanitizeForMermaid("");

        // Assert
        result.Should().BeEmpty();
    }

    [Fact]
    public void SanitizeForMermaid_WithOnlySpecialChars_ReturnsEmpty()
    {
        // Act
        var result = VisualizationTools.SanitizeForMermaid("@#$%^&*()");

        // Assert
        result.Should().BeEmpty();
    }
}
