// <auto-generated>
// This file was generated by Aura Test Generator.
// </auto-generated>

using Xunit;
using NSubstitute;
using FluentAssertions;
using Aura.Module.Developer.Tools;
using Aura.Foundation.Rag;
using Aura.Foundation.Tools;
using Microsoft.Extensions.Logging.Abstractions;

namespace Aura.Module.Developer.Tools.Tests;

public class VisualizationToolsTests
{
    [Fact]
    public void RegisterVisualizationTools_WhenCalled_RegistersToolsInRegistry()
    {
        // Arrange
        var registry = Substitute.For<IToolRegistry>();
        var codeGraphService = Substitute.For<ICodeGraphService>();
        var logger = NullLogger.Instance;

        // Act
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, logger);

        // Assert - should register at least one tool
        registry.Received().RegisterTool(Arg.Any<ToolDefinition>());
    }

    [Fact]
    public void RegisterVisualizationTools_Registers3Tools()
    {
        // Arrange
        var registry = Substitute.For<IToolRegistry>();
        var codeGraphService = Substitute.For<ICodeGraphService>();
        var logger = NullLogger.Instance;

        // Act
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, logger);

        // Assert - registers exactly 3 tools (dependencies, class hierarchy, call graph)
        registry.Received(3).RegisterTool(Arg.Any<ToolDefinition>());
    }

    [Fact]
    public void RegisterVisualizationTools_RegistersDependenciesTool()
    {
        // Arrange
        var registry = Substitute.For<IToolRegistry>();
        var codeGraphService = Substitute.For<ICodeGraphService>();
        var logger = NullLogger.Instance;

        // Act
        VisualizationTools.RegisterVisualizationTools(registry, codeGraphService, logger);

        // Assert
        registry.Received().RegisterTool(Arg.Is<ToolDefinition>(t => t.ToolId == "graph.visualize_dependencies"));
    }
}
