// <auto-generated>
// This file was generated by Aura Test Generator.
// </auto-generated>

using FluentAssertions;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;
using Aura.Module.Developer.Ingestors;

namespace Aura.Module.Developer.Ingestors.Tests;

public class RoslynCodeIngestorTests
{
    private readonly RoslynCodeIngestor _sut;

    public RoslynCodeIngestorTests()
    {
        _sut = new RoslynCodeIngestor(NullLogger<RoslynCodeIngestor>.Instance);
    }

    private RoslynCodeIngestor CreateSut() => new(NullLogger<RoslynCodeIngestor>.Instance);

    [Fact]
    public void CanIngest_WithCSharpFile_ReturnsTrue()
    {
        // Act
        var result = _sut.CanIngest("MyClass.cs");

        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public void CanIngest_WithNonCSharpFile_ReturnsFalse()
    {
        // Act
        var result = _sut.CanIngest("script.py");

        // Assert
        result.Should().BeFalse();
    }

    [Fact]
    public async Task IngestAsync_WithValidCSharpCode_ReturnsChunks()
    {
        // Arrange
        var code = """
            namespace Test;
            public class MyClass
            {
                public void Method() { }
            }
            """;

        // Act
        var result = await _sut.IngestAsync("MyClass.cs", code, CancellationToken.None);

        // Assert
        result.Should().NotBeEmpty();
    }

    [Fact]
    public async Task IngestCodeAsync_WithValidCSharpCode_ReturnsResult()
    {
        // Arrange
        var code = """
            namespace Test;
            public class MyClass
            {
                public string Name { get; set; }
            }
            """;

        // Act
        var result = await _sut.IngestCodeAsync("MyClass.cs", code, "/workspace", CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
    }

    [Fact]
    public void CanIngest_WithVbFile_ReturnsFalse()
    {
        // Act
        var result = _sut.CanIngest("Module1.vb");

        // Assert
        result.Should().BeFalse();
    }

    [Fact]
    public async Task IngestAsync_WithEmptyContent_ReturnsEmptyResult()
    {
        // Act
        var result = await _sut.IngestAsync("Empty.cs", "", CancellationToken.None);

        // Assert
        result.Should().BeEmpty();
    }

    [Theory]
    [InlineData("Test.cs")]
    [InlineData("MyClass.CS")]
    [InlineData("path/to/File.cs")]
    public void CanIngest_WithCSharpFileCaseInsensitive_ReturnsTrue(string filePath)
    {
        // Act
        var result = _sut.CanIngest(filePath);

        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public async Task IngestCodeAsync_WithClassAndMethod_ExtractsSymbols()
    {
        // Arrange
        var code = """
            namespace Test;
            public class Calculator
            {
                public int Add(int a, int b) => a + b;
                public int Subtract(int a, int b) => a - b;
            }
            """;

        // Act
        var result = await _sut.IngestCodeAsync("Calculator.cs", code, "/workspace", CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.Nodes.Should().NotBeEmpty();
    }
}
