// <auto-generated>
// This file was generated by Aura Test Generator.
// </auto-generated>

using Xunit;
using NSubstitute;
using Aura.Module.Developer.Guardians;
using Aura.Foundation.Guardians;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;

namespace Aura.Module.Developer.Guardians.Tests;

public class GuardianRegistryInitializerTests
{

    [Fact]
    public async Task StartAsync_WhenCalled_ReturnsExpectedResult()
    {
        // Arrange
        var _registry = Substitute.For<IGuardianRegistry>();
        var guardianOptions = new GuardianOptions { Directories = [] };
        var _options = Options.Create(guardianOptions);
        var _environment = Substitute.For<IHostEnvironment>();
        _environment.ContentRootPath.Returns("/test");
        var _logger = Substitute.For<ILogger<GuardianRegistryInitializer>>();
        var sut = new GuardianRegistryInitializer(_registry, _options, _environment, _logger);

        // Act
        await sut.StartAsync(CancellationToken.None);

        // Assert
        // Method completed without throwing - add behavior verification if needed
        await _registry.Received(1).ReloadAsync();
    }

    [Fact]
    public async Task StopAsync_WhenCalled_ReturnsExpectedResult()
    {
        // Arrange
        var _registry = Substitute.For<IGuardianRegistry>();
        var _options = Options.Create(new GuardianOptions { Directories = [] });
        var _environment = Substitute.For<IHostEnvironment>();
        var _logger = Substitute.For<ILogger<GuardianRegistryInitializer>>();
        var sut = new GuardianRegistryInitializer(_registry, _options, _environment, _logger);

        // Act
        await sut.StopAsync(CancellationToken.None);

        // Assert - StopAsync completes immediately
    }

    [Fact]
    public async Task StartAsync_WhenAwaited_CompletesSuccessfully()
    {
        // Arrange
        var _registry = Substitute.For<IGuardianRegistry>();
        var guardianOptions = new GuardianOptions { Directories = ["guardians"] };
        var _options = Options.Create(guardianOptions);
        var _environment = Substitute.For<IHostEnvironment>();
        _environment.ContentRootPath.Returns("/test");
        var _logger = Substitute.For<ILogger<GuardianRegistryInitializer>>();
        var sut = new GuardianRegistryInitializer(_registry, _options, _environment, _logger);

        // Act
        await sut.StartAsync(CancellationToken.None);

        // Assert
        // Verify directory was added and reload was called
        _registry.Received(1).AddWatchDirectory(Arg.Any<string>());
        await _registry.Received(1).ReloadAsync();
    }

    [Fact]
    public async Task StopAsync_WhenAwaited_CompletesSuccessfully()
    {
        // Arrange
        var _registry = Substitute.For<IGuardianRegistry>();
        var _options = Options.Create(new GuardianOptions { Directories = [] });
        var _environment = Substitute.For<IHostEnvironment>();
        var _logger = Substitute.For<ILogger<GuardianRegistryInitializer>>();
        var sut = new GuardianRegistryInitializer(_registry, _options, _environment, _logger);

        // Act
        await sut.StopAsync(CancellationToken.None);

        // Assert - StopAsync completes immediately
    }
}
