// <auto-generated>
// This file was generated by Aura Test Generator.
// </auto-generated>

namespace Aura.Module.Developer.Guardians.Tests;

using System.IO.Abstractions.TestingHelpers;
using Aura.Foundation.Guardians;
using Aura.Module.Developer.Guardians;
using FluentAssertions;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;

public class GuardianRegistryTests : IDisposable
{
    private readonly MockFileSystem _fileSystem = new();
    private readonly GuardianRegistry _sut;

    public GuardianRegistryTests()
    {
        _sut = new GuardianRegistry(_fileSystem, NullLogger<GuardianRegistry>.Instance);
    }

    public void Dispose()
    {
        _sut.Dispose();
        GC.SuppressFinalize(this);
    }

    [Fact]
    public void GetGuardian_WithNoGuardians_ReturnsNull()
    {
        // Act
        var result = _sut.GetGuardian("nonexistent");

        // Assert
        result.Should().BeNull();
    }

    [Fact]
    public void GetByTriggerType_WithNoGuardians_ReturnsEmpty()
    {
        // Act
        var result = _sut.GetByTriggerType(GuardianTriggerType.Schedule);

        // Assert
        result.Should().BeEmpty();
    }

    [Fact]
    public void Dispose_CanBeCalledMultipleTimes()
    {
        // Act
        _sut.Dispose();
        var act = () => _sut.Dispose();

        // Assert
        act.Should().NotThrow();
    }

    [Fact]
    public async Task ReloadAsync_WithNoDirectories_CompletesSuccessfully()
    {
        // Act
        await _sut.ReloadAsync();

        // Assert
        _sut.Guardians.Should().BeEmpty();
    }
}
