// <auto-generated />
using System;
using Aura.Module.Developer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aura.Module.Developer.Migrations
{
    [DbContext(typeof(DeveloperDbContext))]
    [Migration("20260119085440_AddWorkflowVerification")]
    partial class AddWorkflowVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aura.Module.Developer.Data.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalyzedContext")
                        .HasColumnType("jsonb")
                        .HasColumnName("analyzed_context");

                    b.Property<string>("AutomationMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("automation_mode");

                    b.Property<string>("ChatHistory")
                        .HasColumnType("jsonb")
                        .HasColumnName("chat_history");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExecutionPlan")
                        .HasColumnType("jsonb")
                        .HasColumnName("execution_plan");

                    b.Property<string>("GitBranch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("git_branch");

                    b.Property<int?>("IssueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("issue_number");

                    b.Property<string>("IssueOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issue_owner");

                    b.Property<string>("IssueProvider")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("issue_provider");

                    b.Property<string>("IssueRepo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issue_repo");

                    b.Property<string>("IssueUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("issue_url");

                    b.Property<string>("PatternLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pattern_language");

                    b.Property<string>("PatternName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pattern_name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("pull_request_url");

                    b.Property<string>("RepositoryPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("repository_path");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceGuardianId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedCapability")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("VerificationPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("VerificationResult")
                        .HasColumnType("text");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("worktree_path");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IssueUrl");

                    b.HasIndex("Status");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("Aura.Module.Developer.Data.Entities.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Approval")
                        .HasColumnType("integer")
                        .HasColumnName("approval");

                    b.Property<string>("ApprovalFeedback")
                        .HasColumnType("text")
                        .HasColumnName("approval_feedback");

                    b.Property<string>("AssignedAgentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_agent_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("capability");

                    b.Property<string>("ChatHistory")
                        .HasColumnType("jsonb")
                        .HasColumnName("chat_history");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Input")
                        .HasColumnType("jsonb")
                        .HasColumnName("input");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<bool>("NeedsRework")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_rework");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Output")
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<string>("PreviousOutput")
                        .HasColumnType("jsonb")
                        .HasColumnName("previous_output");

                    b.Property<string>("SkipReason")
                        .HasColumnType("text")
                        .HasColumnName("skip_reason");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowId", "Order");

                    b.ToTable("workflow_steps", (string)null);
                });

            modelBuilder.Entity("Aura.Module.Developer.Data.Entities.WorkflowStep", b =>
                {
                    b.HasOne("Aura.Module.Developer.Data.Entities.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Aura.Module.Developer.Data.Entities.Workflow", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
