// <auto-generated>
// This file was generated by Aura Test Generator and enhanced manually.
// </auto-generated>

#nullable enable

using Aura.Foundation.Agents;
using Aura.Foundation.Tools;
using Aura.Module.Developer;
using FluentAssertions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using NSubstitute;
using Xunit;

namespace Aura.Module.Developer.Tests;

public class DeveloperModuleTests
{
    private readonly DeveloperModule _sut;

    public DeveloperModuleTests()
    {
        _sut = new DeveloperModule();
    }

    [Fact]
    public void ModuleId_ShouldReturnDeveloper()
    {
        _sut.ModuleId.Should().Be("developer");
    }

    [Fact]
    public void Name_ShouldReturnDeveloperWorkflow()
    {
        _sut.Name.Should().Be("Developer Workflow");
    }

    [Fact]
    public void Description_ShouldReturnExpectedDescription()
    {
        _sut.Description.Should().Contain("Code automation");
    }

    [Fact]
    public void Dependencies_ShouldBeEmpty()
    {
        _sut.Dependencies.Should().BeEmpty();
    }

    [Fact]
    public void ConfigureServices_WithValidParameters_ShouldNotThrow()
    {
        // Arrange
        var services = new ServiceCollection();
        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["ConnectionStrings:auradb"] = "Host=localhost;Database=test"
            })
            .Build();

        // Act
        var act = () => _sut.ConfigureServices(services, config);

        // Assert
        act.Should().NotThrow();
    }

    [Fact]
    public void ConfigureServices_ShouldRegisterExpectedServices()
    {
        // Arrange
        var services = new ServiceCollection();
        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["ConnectionStrings:auradb"] = "Host=localhost;Database=test"
            })
            .Build();

        // Act
        _sut.ConfigureServices(services, config);

        // Assert
        services.Should().Contain(sd => sd.ServiceType.Name == "IWorkflowService");
        services.Should().Contain(sd => sd.ServiceType.Name == "IRoslynWorkspaceService");
        services.Should().Contain(sd => sd.ServiceType.Name == "IRoslynRefactoringService");
    }

    [Fact]
    public void RegisterAgents_WithValidRegistry_ShouldNotThrow()
    {
        // Arrange
        var registry = Substitute.For<IAgentRegistry>();
        var config = new ConfigurationBuilder().Build();

        // Act
        var act = () => _sut.RegisterAgents(registry, config);

        // Assert
        act.Should().NotThrow();
    }

    [Fact]
    public void RegisterAgents_WhenAgentsPathConfigured_ShouldNotThrow()
    {
        // Arrange
        var registry = Substitute.For<IAgentRegistry>();
        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["Aura:Modules:Developer:AgentsPath"] = "./custom-agents"
            })
            .Build();

        // Act
        var act = () => _sut.RegisterAgents(registry, config);

        // Assert - Currently a no-op as per TODO, but should not throw
        act.Should().NotThrow();
    }
}
