// <auto-generated />
using System;
using System.Collections.Generic;
using Aura.Foundation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Aura.Foundation.Data.Migrations
{
    [DbContext(typeof(AuraDbContext))]
    partial class AuraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aura.Foundation.Data.Entities.AgentExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_id");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input");

                    b.Property<string>("Output")
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.HasKey("Id")
                        .HasName("pk_agent_executions");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_agent_executions_agent_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_agent_executions_started_at");

                    b.ToTable("agent_executions", (string)null);
                });

            modelBuilder.Entity("Aura.Foundation.Data.Entities.CodeEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relationship_type");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_node_id");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_node_id");

                    b.HasKey("Id")
                        .HasName("pk_code_edges");

                    b.HasIndex("RelationshipType")
                        .HasDatabaseName("ix_code_edges_relationship_type");

                    b.HasIndex("SourceNodeId")
                        .HasDatabaseName("ix_code_edges_source_node_id");

                    b.HasIndex("TargetNodeId")
                        .HasDatabaseName("ix_code_edges_target_node_id");

                    b.ToTable("code_edges", (string)null);
                });

            modelBuilder.Entity("Aura.Foundation.Data.Entities.CodeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<string>("FullyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fully_qualified_name");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("node_type");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("SourceCode")
                        .HasColumnType("text")
                        .HasColumnName("source_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_code_nodes");

                    b.HasIndex("FullyQualifiedName")
                        .IsUnique()
                        .HasDatabaseName("ix_code_nodes_fully_qualified_name");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_code_nodes_name");

                    b.HasIndex("NodeType")
                        .HasDatabaseName("ix_code_nodes_node_type");

                    b.ToTable("code_nodes", (string)null);
                });

            modelBuilder.Entity("Aura.Foundation.Data.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_conversations_created_at");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("Aura.Foundation.Data.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("Source")
                        .IsUnique()
                        .HasDatabaseName("ix_documents_source");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Aura.Foundation.Data.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.HasKey("Id")
                        .HasName("pk_document_chunks");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_chunks_document_id");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("Aura.Foundation.Data.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_messages_conversation_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Aura.Foundation.Data.Entities.CodeEdge", b =>
                {
                    b.HasOne("Aura.Foundation.Data.Entities.CodeNode", "SourceNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_code_edges_code_nodes_source_node_id");

                    b.HasOne("Aura.Foundation.Data.Entities.CodeNode", "TargetNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_code_edges_code_nodes_target_node_id");

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("Aura.Foundation.Data.Entities.DocumentChunk", b =>
                {
                    b.HasOne("Aura.Foundation.Data.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_chunks_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Aura.Foundation.Data.Entities.Message", b =>
                {
                    b.HasOne("Aura.Foundation.Data.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Aura.Foundation.Data.Entities.CodeNode", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");
                });

            modelBuilder.Entity("Aura.Foundation.Data.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Aura.Foundation.Data.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
