// <auto-generated>
// This file was generated by Aura Test Generator.
// </auto-generated>

using Xunit;
using NSubstitute;
using Aura.Module.Developer.Services.Testing;
using Aura.Module.Developer.Services;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;

namespace Aura.Module.Developer.Services.Testing.Tests;

public class RoslynTestGeneratorTests
{

    [Fact]
    public async Task GenerateTestsAsync_WhenCalled_ReturnsExpectedResult()
    {
        // Arrange
        var request = new TestGenerationRequest { Target = "test-target", SolutionPath = "test-solutionpath" };
        var _workspaceService = Substitute.For<IRoslynWorkspaceService>();
        var _logger = Substitute.For<ILogger<RoslynTestGenerator>>();
        var sut = new RoslynTestGenerator(_workspaceService, _logger);

        // Act
        var result = await sut.GenerateTestsAsync(request, CancellationToken.None);

        // Assert
        Assert.NotNull(result);
    }

    [Fact]
    public async Task GenerateTestsAsync_WhenAwaited_CompletesSuccessfully()
    {
        // Arrange
        var request = new TestGenerationRequest { Target = "test-target", SolutionPath = "test-solutionpath" };
        var _workspaceService = Substitute.For<IRoslynWorkspaceService>();
        var _logger = Substitute.For<ILogger<RoslynTestGenerator>>();
        var sut = new RoslynTestGenerator(_workspaceService, _logger);

        // Act
        var result = await sut.GenerateTestsAsync(request, CancellationToken.None);

        // Assert
        Assert.NotNull(result);
    }
}
